apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: your-ecr-url/backend:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: db-secret
        - configMapRef:
            name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80